name: 'Setup Poetry with Cache'
description: 'Setup poetry with daily cache. Cache based not on lock file but pyproject.toml.'
author: 'Sho Iwamoto'
inputs:
  python-version:
    description: 'Python version to install'
    required: true
  architecture:
    description: 'Architecture passed to setup-python'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"
      shell: bash
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
        architecture: ${{ inputs.architecture }}
    - name: Load cached Poetry installation
      if: runner.os == 'Linux'
      uses: actions/cache@v2
      with:
        path: ~/.local
        key: poetry-Linux-${{ inputs.python-version }}-${{ steps.date.outputs.date }}
    - name: Set up Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        virtualenvs-path: '.venv'
    - name: Load cached venv
      id: load-cache
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ steps.date.outputs.date }}-${{ hashFiles('pyproject.toml') }}
    - name: Set up Dependencies
      if: steps.load-cache.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root
      shell: bash

