#!env python3

import pathlib
import re
import sys

re_doubled_cite = re.compile(r"\\cite\{(.*?)\}\\cite\{(.*?)\}")


def finalize(text):
    text = re.sub(r"^\\autogeneratedwarning", "", text, flags=re.M)
    text = finalize_section_tt(text)
    text = finalize_index_tt(text)
    text = finalize_cite(text)
    return text


def finalize_cite(text):
    doubled_cite_match = re_doubled_cite.search(text)
    if doubled_cite_match:
        text = re_doubled_cite.sub(r"\\cite{\1,\2}", text)
        text = finalize_cite(text)
    return text


def finalize_section_tt(text):
    re_content_sub = re.compile(r"(susy\\_cross\\_section[^ ]*)")

    def sub(match):
        return "\\relax" + re_content_sub.sub(r"\\texttt{\1}", match.group(0))

    for t in ["section", "subsection", "subsubsection"]:
        regexp = r"^\\(" + t + r")\{.*\}"
        text = re.sub(regexp, sub, text, flags=re.M)

    return text


def finalize_index_tt(text):
    re1 = re.compile(r"\A(susy\\_cross\\_section\..+) class method\Z")
    re2 = re.compile(r"\A(.+) (method|static method)\Z")
    re3 = re.compile(r"\A(class in|in module) (susy\\_cross\\_section\.[^ ]+)\Z")

    def t(text):
        return "\\finalizedspxextra{" + text + "}"

    def sub(match):
        b = match.group(1)
        m1 = re1.match(b)
        if m1:
            return t("\\texttt{" + m1.group(1) + "} class method")
        m2 = re2.match(b)
        if m2:
            return t("\\texttt{" + m2.group(1) + "} " + m2.group(2))
        m3 = re3.match(b)
        if m3:
            return t(m3.group(1) + " \\texttt{" + m3.group(2) + "}")
        return t(b)

    return re.sub(r"\\spxextra\{(.*?)\}", sub, text)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} [TEX_FILE]", file=sys.stderr)
        exit(1)

    target = pathlib.Path(sys.argv[1])
    text = target.read_text()
    target.write_text(finalize(text))
    exit(0)
