name: TypeCheck

permissions:
  checks: write
  pull-requests: write

on:
  workflow_run:
    workflows: [Test]
    types: [completed]
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]
      fail-fast: false
    env:
      PYTHON: ${{ matrix.python-version }}
    name: Execute on Python ${{ matrix.python-version }}
    steps:
      - name: Quit if test-failure
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: exit 1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up environment
        uses: ./.github/actions/setup-poetry-with-cache
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Run
        id: run
        run: |
          source $VENV
          mypy -p susy_cross_section --junit-xml=mypy_${PYTHON}.xml
        continue-on-error: true
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: Result (Python ${{ matrix.python-version }})
          path: '*.xml'

  publish-results:
    name: "Publish Results"
    needs: execute
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: |
            artifacts/**/mypy_*.xml
          check_name: 'TypeCheck Results'
          event_name: 'TypeCheck'
